// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXogUJ4ytqmcBAXuxdIoRmrYk5FNptuz8',
    appId: '1:1061239060390:web:ef0ce995a693d0bd54c167',
    messagingSenderId: '1061239060390',
    projectId: 'fir-login-6137b',
    authDomain: 'fir-login-6137b.firebaseapp.com',
    storageBucket: 'fir-login-6137b.appspot.com',
    measurementId: 'G-Q3MLQMWSZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-MEhwIJzNKSg38VXGd_P7JewKZaYQU0',
    appId: '1:1061239060390:android:29df553389b4f2db54c167',
    messagingSenderId: '1061239060390',
    projectId: 'fir-login-6137b',
    storageBucket: 'fir-login-6137b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESgSW2JlW-GrujKAhL3haGlxriOTSKjE',
    appId: '1:1061239060390:ios:51622c0d75ac790354c167',
    messagingSenderId: '1061239060390',
    projectId: 'fir-login-6137b',
    storageBucket: 'fir-login-6137b.appspot.com',
    iosBundleId: 'com.example.loginFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESgSW2JlW-GrujKAhL3haGlxriOTSKjE',
    appId: '1:1061239060390:ios:f5b2ea23657aa2e554c167',
    messagingSenderId: '1061239060390',
    projectId: 'fir-login-6137b',
    storageBucket: 'fir-login-6137b.appspot.com',
    iosBundleId: 'com.example.loginFirebaseApp.RunnerTests',
  );
}
